GET http://localhost:2828/user-api/get-users
Content-Type: application/json

###REGISTER A USER
POST http://localhost:2828/user-api/register-user
Content-Type: application/json

{
    "firstName":"harsha",
    "lastName":"biddika",
    "email":"harsha@gmail.com",
    "role":"user",
    "password":"harsha"
}

###LOGIN
POST http://localhost:2828/user-api/login
Content-Type: application/json

{
    "email":"harsha@gmail.com",
    "password":"harsha"
}

###
POST http://localhost:2828/restaurant-api/restaurants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnNoYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NTUxMDk5MywiZXhwIjoxNjg1NTk3MzkzfQ.9UmoKFzaunQD544DsJGke38u5ys53CB_TQt1_hqGG9g
Content-Type: application/json

{
    "name":"Food court",
    "createdBy":"Admin",
    "updatedBy":"Admin"
    
}

###Get restaurants by pagination
GET http://localhost:2828/restaurant-api/get-restaurant/1/3

###search restaurants on criteria
POST http://localhost:2828/restaurant-api/search-restaurant
Content-Type: application/json

{
    "name":"Food Court"
}

###
DELETE http://localhost:2828/user-api/delete-restaurant/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRheWFuYWRAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjg1NDQ0ODU4LCJleHAiOjE2ODU1MzEyNTh9.EcnsCCRezdj9LcripolLVxsrc36EnLSMUZlkS8e_LIw
